package app.reading.lifearc.transit;

public enum MonthlyTransitActivationReason {
    TARGET_ANNUAL_PROFECTED_SIGN,
    TARGET_ANNUAL_PROFECTED_HOUSE,
    TARGET_MONTHLY_PROFECTED_SIGN,
    TARGET_MONTHLY_PROFECTED_HOUSE,
    TARGET_LORD_OF_YEAR_NATAL_POINT,
    TARGET_LORD_OF_MONTH_NATAL_POINT,
    TARGET_LOT_IN_ANNUAL_PROFECTED_SIGN,
    TARGET_LOT_IN_MONTHLY_PROFECTED_SIGN,
    TRANSIT_LORD_OF_YEAR,
    TRANSIT_LORD_OF_MONTH,
    TRANSIT_IN_ANNUAL_PROFECTED_SIGN,
    TRANSIT_IN_MONTHLY_PROFECTED_SIGN,
    TRANSIT_OVERLAYING_ANNUAL_PROFECTED_HOUSE,
    TRANSIT_OVERLAYING_MONTHLY_PROFECTED_HOUSE
}
